### PR TITLE
ES6 is cute, but not easy to transpile in node_modules

### PR DESCRIPTION
**Pull request by void--**

### CODE REVIEW

**Comment by a9b3** [comment]
@void--  doesn't hurt to just use anonymous functions but, if your project is already using babel to transpile shouldn't this still work? just wondering

**Comment by void--** [comment]
I thought the same thing, but apparently not ¯\_(ツ)_/¯ I'm using create-react-app and their babel configuration doesn't seem to transpile node modules. I didn't want to eject so I had to fork the repo. Hey, thanks for the hard work btw, don't know if I would have figured this out on my own :)

**Comment by a9b3** [comment]
@void-- yeah dude np!

**Comment by a9b3** [comment]
@void-- fyi, published 0.2.0 with this change

**Pull request merged**
